#!/usr/bin/php -f
<?php

/* Include the bot's core, this is where a lot of the important stuff
 * is done and the only required file from a user's point of view.
 */
include('src/core.php');

/* Create a new instance of Erebot and call its start() method to actually
 * start the bot. You may pass an instance of ErebotMainConfig to the
 * constructor. If you don't, the bpt will try to load its configuration
 * automatically from a file called "config.xml" in this folder.
 */
$bot = new Erebot();
$bot->start();

?>
