<?php

/**

\page tests             Unit tests
    This text is a placeholder for the real page,
    which is automatically generated by make.

\page scenarii          Behavioural tests
    This text is a placeholder for the real page,
    which is automatically generated by make.

\page coverage/index    Coverage reports
    This text is a placeholder for the real page,
    which is automatically generated by make.

*/

?>
